// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domains "todo-clone/modules/domains"
import gorm "gorm.io/gorm"
import mock "github.com/stretchr/testify/mock"

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

// Create provides a mock function with given fields: item
func (_m *Creator) Create(item *domains.Item) *gorm.DB {
	ret := _m.Called(item)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*domains.Item) *gorm.DB); ok {
		r0 = rf(item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}
