// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gorm "gorm.io/gorm"
import mock "github.com/stretchr/testify/mock"

// Finder is an autogenerated mock type for the Finder type
type Finder struct {
	mock.Mock
}

// Find provides a mock function with given fields: offset, limit
func (_m *Finder) Find(offset int, limit int) *gorm.DB {
	ret := _m.Called(offset, limit)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(int, int) *gorm.DB); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}
