// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domains "todo-clone/modules/domains"
import gorm "gorm.io/gorm"
import mock "github.com/stretchr/testify/mock"

// Firster is an autogenerated mock type for the Firster type
type Firster struct {
	mock.Mock
}

// First provides a mock function with given fields: item, id
func (_m *Firster) First(item *domains.Item, id uint64) *gorm.DB {
	ret := _m.Called(item, id)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*domains.Item, uint64) *gorm.DB); ok {
		r0 = rf(item, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}
