definitions:
  controller.Body:
    properties:
      title:
        type: string
    type: object
  domains.Item:
    properties:
      checked:
        type: boolean
      created:
        type: string
      id:
        type: integer
      title:
        type: string
      updated:
        type: string
    type: object
info:
  contact: {}
paths:
  /todos:
    get:
      description: find all todo items
      operationId: todo-get-all
      parameters:
      - default: 10
        example: 10
        in: query
        minimum: 1
        name: limit
        type: integer
      - default: 1
        example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: find all todo items
      tags:
      - todo
    post:
      description: todo post
      operationId: todo-post
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.Body'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Item'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: todo post
      tags:
      - todo
  /todos/{id}:
    delete:
      description: todo delete
      operationId: todo-delete
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: todo delete
      tags:
      - todo
    get:
      description: todo get
      operationId: todo-get
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Item'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: todo get
      tags:
      - todo
    patch:
      description: todo patch
      operationId: todo-patch
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.Body'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: todo patch
      tags:
      - todo
swagger: "2.0"
